/** Aligné sur l’enum `Role` du bot Discord. */
export const BOT_ROLE_KEYS = [
  'WEREWOLF',
  'VILLAGER',
  'SEER',
  'WITCH',
  'HUNTER',
  'CUPID',
  'GUARD',
  'THIEF',
  'ANGEL',
  'LITTLE_GIRL',
  'RAVEN',
  'RED_RIDING_HOOD',
  'FOOL_OF_VILLAGE',
  'ELDER',
  'BIG_BAD_WOLF',
  'WHITE_WEREWOLF',
  'PIED_PIPER',
  'RUSTY_SWORD_KNIGHT',
  'SCAPEGOAT',
  'WILD_CHILD',
  'FOX',
  'PYROMANIAC',
  'BEAR_TAMER',
  'TWO_SISTERS',
  'THREE_BROTHERS',
] as const;

export type BotRoleKey = (typeof BOT_ROLE_KEYS)[number];

export const BOT_ROLE_LABELS_FR: Record<BotRoleKey, string> = {
  WEREWOLF: 'Loup-Garou',
  VILLAGER: 'Villageois',
  SEER: 'Voyante',
  WITCH: 'Sorcière',
  HUNTER: 'Chasseur',
  CUPID: 'Cupidon',
  GUARD: 'Garde',
  THIEF: 'Voleur',
  ANGEL: 'Ange',
  LITTLE_GIRL: 'Petite fille',
  RAVEN: 'Corbeau',
  RED_RIDING_HOOD: 'Chaperon Rouge',
  FOOL_OF_VILLAGE: 'Idiot du village',
  ELDER: 'Ancien',
  BIG_BAD_WOLF: 'Grand Méchant Loup',
  WHITE_WEREWOLF: 'Loup-Blanc',
  PIED_PIPER: 'Joueur de Flûte',
  RUSTY_SWORD_KNIGHT: "Chevalier à l'épée rouillée",
  SCAPEGOAT: 'Bouc Émissaire',
  WILD_CHILD: 'Enfant Sauvage',
  FOX: 'Renard',
  PYROMANIAC: 'Pyromane',
  BEAR_TAMER: "Montreur d\u2019Ours",
  TWO_SISTERS: 'Deux S\u0153urs',
  THREE_BROTHERS: 'Trois Fr\u00e8res',
};

export const BOT_ROLE_DESCRIPTIONS_FR: Record<BotRoleKey, string> = {
  WEREWOLF: 'Chaque nuit, les loups-garous se réveillent et choisissent un villageois à dévorer. Ils doivent rester discrets le jour.',
  VILLAGER: 'Simple villageois sans pouvoir spécial. Son seul atout : son vote le jour pour éliminer les loups-garous.',
  SEER: 'Chaque nuit, la voyante peut espionner un joueur et découvrir sa véritable identité. Pouvoir crucial mais dangereux si les loups la repèrent.',
  WITCH: 'La sorcière possède deux potions : une de guérison et une de mort. Chacune est utilisable une seule fois dans la partie.',
  HUNTER: 'Quand le chasseur est éliminé, il tire une dernière balle sur le joueur de son choix. Un pouvoir qui peut renverser la partie.',
  CUPID: 'En début de partie, Cupidon désigne deux amoureux. Si l\'un meurt, l\'autre meurt aussi de chagrin.',
  GUARD: 'Chaque nuit, le garde protège un joueur de l\'attaque des loups-garous. Il ne peut pas protéger la même personne deux nuits de suite.',
  THIEF: 'En début de partie, le voleur choisit entre deux cartes face cachée pour échanger son rôle.',
  ANGEL: 'L\'ange gagne s\'il est éliminé au premier vote du village. S\'il survit, il devient un simple villageois.',
  LITTLE_GIRL: 'La petite fille peut espionner les loups-garous pendant la nuit en entrouvrant les yeux, mais gare à se faire repérer.',
  RAVEN: 'Chaque nuit, le corbeau désigne un joueur qui recevra +2 votes supplémentaires lors du vote du village le lendemain. Le salon annonce qu\'un joueur a été marqué, sans révéler l\'identité du corbeau.',
  RED_RIDING_HOOD: 'Tant que le Chasseur est en vie, les loups ne peuvent pas dévorer le Chaperon Rouge (attaque absorbée — personne ne meurt). Si le Chasseur meurt, cette protection disparaît. Pouvoir entièrement passif, sans action nocturne.',
  FOOL_OF_VILLAGE: 'Si le village vote pour l\'éliminer, l\'Idiot du village ne meurt pas (une seule fois). Son identité est révélée publiquement et il perd son droit de vote pour le reste de la partie. Il peut toutefois être mangé par les loups ou tué par d\'autres effets.',
  ELDER: 'L\'Ancien peut survivre à la première attaque des loups (annoncé comme une résistance mystérieuse, sans révéler son identité). Si le village le vote pour l\'éliminer, tous les rôles spéciaux du camp Village perdent leurs pouvoirs pour le reste de la partie.',
  BIG_BAD_WOLF: "Vote chaque nuit avec la meute comme un loup-garou. En plus, tant qu'aucun loup n'est mort, il peut tuer un joueur supplémentaire seul dans son fil privé. Si un loup meurt, il perd ce pouvoir bonus mais continue de jouer avec la meute.",
  WHITE_WEREWOLF: "Joue comme un loup ordinaire (vote avec la meute). Toutes les nuits paires, il peut éliminer secrètement un loup-garou de la meute. Il gagne seul s'il est le dernier survivant de la partie.",
  PIED_PIPER: "Chaque nuit, le Joueur de Flûte ensorcelle 2 joueurs vivants (non encore ensorcelés) via son fil privé. Il gagne seul quand tous les survivants (sauf lui) sont ensorcelés. Si le Joueur de Flûte meurt, les enchantements restent mais sa condition de victoire disparaît.",
  RUSTY_SWORD_KNIGHT: "Pouvoir entièrement passif : si le Chevalier est dévoré par les loups (attaque de meute), le premier loup-garou par ordre alphabétique meurt d'une infection mystérieuse à l'aube suivante. La Sorcière peut annuler la mort du Chevalier, ce qui annule aussi l'infection.",
  SCAPEGOAT: "Pouvoir entièrement passif : en cas d'égalité au vote du village, c'est le Bouc Émissaire qui est éliminé à la place (prioritaire sur le tirage au sort). Après sa mort, il choisit quels joueurs pourront (ou ne pourront pas) voter lors du prochain vote.",
  WILD_CHILD: "La premi\u00e8re nuit, l'Enfant Sauvage choisit un joueur comme mod\u00e8le. Si son mod\u00e8le meurt \u00e0 n'importe quel moment, l'Enfant Sauvage se transforme en Loup-Garou et rejoint la meute. Tant que le mod\u00e8le est en vie, il joue du c\u00f4t\u00e9 du village.",
  FOX: "Chaque nuit, le Renard choisit 3 joueurs \u00e0 flairer. Le bot lui dit si au moins l'un d'eux est un loup-garou (oui/non), sans pr\u00e9ciser lequel. Si la r\u00e9ponse est non, il perd son pouvoir d\u00e9finitivement mais reste en jeu du c\u00f4t\u00e9 du village.",
  PYROMANIAC: "Camp Solo. Chaque nuit, le Pyromane arrose un joueur d'essence (ou lui-m\u00eame). Quand il le d\u00e9cide, il d\u00e9clenche l'incendie : tous les joueurs arros\u00e9s encore en vie meurent simultan\u00e9ment. Il gagne seul si tous les autres joueurs vivants sont arros\u00e9s, ou s'il est le dernier survivant.",
  BEAR_TAMER: "R\u00f4le passif. La nuit 1, 2 joueurs sont assign\u00e9s comme voisins secrets (al\u00e9atoires). \u00c0 chaque aube, si l'un des voisins encore en vie est un loup-garou, l'ours grogne publiquement. Le silence est aussi informatif. Montreur d\u2019Ours gagne avec le village.",
  TWO_SISTERS: "Vous \u00eates deux joueuses avec ce r\u00f4le. La premi\u00e8re nuit, vous vous reconnaissez dans un fil priv\u00e9 partag\u00e9. Aucun pouvoir actif — vous vous connaissez simplement. Vous gagnez avec le camp Village.",
  THREE_BROTHERS: "Vous \u00eates trois joueurs avec ce r\u00f4le. La premi\u00e8re nuit, vous vous reconnaissez dans un fil priv\u00e9 partag\u00e9. Aucun pouvoir actif — vous vous connaissez simplement. Vous gagnez avec le camp Village.",
};

export const BOT_ROLE_CAMPS: Record<BotRoleKey, 'loup' | 'village' | 'solo'> = {
  WEREWOLF: 'loup',
  VILLAGER: 'village',
  SEER: 'village',
  WITCH: 'village',
  HUNTER: 'village',
  CUPID: 'village',
  GUARD: 'village',
  THIEF: 'village',
  ANGEL: 'solo',
  LITTLE_GIRL: 'village',
  RAVEN: 'village',
  RED_RIDING_HOOD: 'village',
  FOOL_OF_VILLAGE: 'village',
  ELDER: 'village',
  BIG_BAD_WOLF: 'loup',
  WHITE_WEREWOLF: 'solo',
  PIED_PIPER: 'solo',
  RUSTY_SWORD_KNIGHT: 'village',
  SCAPEGOAT: 'village',
  WILD_CHILD: 'village',
  FOX: 'village',
  PYROMANIAC: 'solo',
  BEAR_TAMER: 'village',
  TWO_SISTERS: 'village',
  THREE_BROTHERS: 'village',
};

export function isBotRoleKey(s: string): s is BotRoleKey {
  return (BOT_ROLE_KEYS as readonly string[]).includes(s);
}



